apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-brty
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-brty
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-brty
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-brty
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-brty
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lbbx-tenant/rhtap-demo-app/hacbs-test-project-brty@sha256:d083633e50b3880af316eb9e4726c82b804770a2636541fa89dfca012a94b939
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
